### ISSUE TITLE
Persist data when using docker

### ISSUE THREAD

**Issue by enric1994** [overshard/timestrap#150]
I would like to persist my data when I do docker-compose down -v
**Which module should I mount in my host?**
Here's my actual docker-compose.yml
```
version: '2'

services:

#Timestrap
  timestrap:
    image: stianovrevage/timestrap:latest
    volumes:
      - ./timestrap-database/:/timestrap/database/
    ports:
      - 8000:8000
    restart: always
```

Ty
